name: schedule

on:
  schedule:
    - cron: '*/2 * * * *'


jobs:
  hello_world:
    runs-on: ubunti-latest
    steps:
      - name: Echo current time
        run: echo "the current server time is $(date)"
    
